# Generated by Django 2.2.5 on 2019-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('title', models.CharField(max_length=512)),
                ('rating', models.PositiveSmallIntegerField()),
                ('duration', models.DurationField()),
                ('director', models.CharField(max_length=512)),
                ('genre', models.CharField(max_length=16)),
            ],
        ),
    ]
